name: GitLab Runner Service
description: 'Runs a gitlab runner privileged mode for a gitlab job'
author: 'Ederson Brilhante'
inputs:
  registration_token:
    description: 'registration token'
    required: true
  runner_name:
    description: 'gitlab runner name'
    required: true
  tag_list:
    description: 'tag list'
    required: true
  docker_image:
    description: 'docker image'
    required: false
    default: 'docker:19.03.12'
branding:
  icon: 'server'
  color: 'purple'
runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/gitlab-runner.sh
      env:
        REGISTRATION_TOKEN: ${{ inputs.registration_token }}
        DOCKER_IMAGE: ${{ inputs.docker_image }}
        RUNNER_NAME: ${{ inputs.runner_name }}
        TAG_LIST: ${{ inputs.tag_list }}
      shell: bash
